theme: jekyll-theme-dinky
title: CodeClinic@CABHC
email: test@test.com
description: Info and resources for the Code Clinic sessions held at the Center for Advanced Biomaterials for Healthcare in Naples (Italy)
url: https://leo-gg.github.io/CodeClinicCABHC/
site.baseurl: /CodeClinicCABHC
